"""Deployment adapters for static AIGC Pack Registries."""
from __future__ import annotations

import hmac
import json
import os
import shutil
import tempfile
import uuid
from dataclasses import dataclass
from hashlib import sha256
from pathlib import Path, PurePosixPath
from typing import Protocol
from urllib.parse import urlparse

from .pack_manager import PackError
from .pack_publisher import _inspect_archive, _validate_release_manifest
from .pack_registry import MAX_ARCHIVE_BYTES, MAX_INDEX_BYTES, RegistryIndex

_DEPLOYMENT_MARKER = ".aigc-registry-deployment.json"
_WORKFLOW_MARKER = "# Generated by AIGC Harness. Re-run `pack deploy github-pages` to update."


@dataclass(frozen=True)
class RegistryDeployment:
    provider: str
    source: Path
    output: Path
    index: Path
    archives: tuple[Path, ...]
    workflow: Path | None = None

    def to_dict(self) -> dict[str, object]:
        return {
            "provider": self.provider,
            "source": str(self.source),
            "output": str(self.output),
            "index": str(self.index),
            "archives": [str(path) for path in self.archives],
            "workflow": str(self.workflow) if self.workflow else None,
        }


class RegistryDeploymentAdapter(Protocol):
    """Provider boundary for preparing a static Registry deployment."""

    provider: str

    def prepare(
        self,
        registry_root: Path,
        output_root: Path,
        *,
        workflow_path: Path | None = None,
        site_path: str | None = None,
    ) -> RegistryDeployment: ...


class GitHubPagesAdapter:
    """Prepare validated static files and an optional GitHub Pages workflow."""

    provider = "github-pages"

    def prepare(
        self,
        registry_root: Path,
        output_root: Path,
        *,
        workflow_path: Path | None = None,
        site_path: str | None = None,
    ) -> RegistryDeployment:
        source = registry_root.expanduser().resolve()
        output = output_root.expanduser().resolve()
        relative_site = site_path or (_default_site_path(output_root) if workflow_path is not None else None)
        if relative_site is not None:
            relative_site = _safe_repository_path(relative_site)
        _validate_distinct_directories(source, output)
        index, relative_archives = validate_static_registry(source)

        output.parent.mkdir(parents=True, exist_ok=True)
        temporary = Path(tempfile.mkdtemp(prefix=f".{output.name}.", dir=output.parent))
        try:
            shutil.copyfile(source / "index.json", temporary / "index.json")
            for relative in relative_archives:
                target = temporary.joinpath(*relative.parts)
                target.parent.mkdir(parents=True, exist_ok=True)
                shutil.copyfile(source.joinpath(*relative.parts), target)
            (temporary / ".nojekyll").write_bytes(b"")
            (temporary / _DEPLOYMENT_MARKER).write_text(
                json.dumps(
                    {"schema_version": 1, "provider": self.provider},
                    ensure_ascii=True,
                    indent=2,
                    sort_keys=True,
                )
                + "\n",
                encoding="utf-8",
            )
            _replace_managed_directory(temporary, output)
        finally:
            if temporary.exists():
                shutil.rmtree(temporary)

        written_workflow: Path | None = None
        if workflow_path is not None:
            assert relative_site is not None
            written_workflow = write_github_pages_workflow(workflow_path, relative_site)
        return RegistryDeployment(
            provider=self.provider,
            source=source,
            output=output,
            index=output / "index.json",
            archives=tuple(output.joinpath(*relative.parts) for relative in relative_archives),
            workflow=written_workflow,
        )


def validate_static_registry(registry_root: Path) -> tuple[RegistryIndex, tuple[PurePosixPath, ...]]:
    """Validate a local static Registry and every archive referenced by its index."""
    root = registry_root.expanduser().resolve()
    index_path = root / "index.json"
    if index_path.is_symlink() or not index_path.is_file():
        raise PackError(f"Pack Registry index does not exist: {index_path}")
    payload = index_path.read_bytes()
    if len(payload) > MAX_INDEX_BYTES:
        raise PackError(f"Pack Registry index exceeds {MAX_INDEX_BYTES} bytes")
    index = RegistryIndex.from_bytes(payload)

    relative_archives: list[PurePosixPath] = []
    seen_paths: set[PurePosixPath] = set()
    for release in index.releases:
        relative = _safe_archive_path(release.archive_url)
        if relative in seen_paths:
            raise PackError(f"Pack Registry references an archive more than once: {relative}")
        seen_paths.add(relative)
        archive = _resolve_registry_file(root, relative)
        if not archive.is_file():
            raise PackError(f"Pack Registry archive does not exist: {relative}")
        archive_payload = archive.read_bytes()
        if len(archive_payload) > MAX_ARCHIVE_BYTES:
            raise PackError(f"Pack Registry archive exceeds {MAX_ARCHIVE_BYTES} bytes: {relative}")
        digest = sha256(archive_payload).hexdigest()
        if not hmac.compare_digest(digest, release.archive_sha256):
            raise PackError(f"Pack Registry archive SHA-256 mismatch: {relative}")
        manifest = _inspect_archive(archive_payload)
        _validate_release_manifest(manifest, release)
        relative_archives.append(relative)
    return index, tuple(sorted(relative_archives, key=str))


def write_github_pages_workflow(path: Path, site_path: str) -> Path:
    """Write a least-privilege, manually triggered GitHub Pages workflow."""
    normalized_site_path = _safe_repository_path(site_path)
    payload = _github_pages_workflow(normalized_site_path)
    target = path.expanduser()
    if target.exists():
        existing = target.read_text(encoding="utf-8")
        if existing == payload:
            return target.resolve()
        if not existing.startswith(_WORKFLOW_MARKER):
            raise PackError(f"Refusing to overwrite a workflow not managed by AIGC Harness: {target}")
    target.parent.mkdir(parents=True, exist_ok=True)
    temporary = target.with_name(f".{target.name}.{uuid.uuid4().hex}.tmp")
    try:
        temporary.write_text(payload, encoding="utf-8")
        os.replace(temporary, target)
    finally:
        temporary.unlink(missing_ok=True)
    return target.resolve()


def _safe_archive_path(value: str) -> PurePosixPath:
    parsed = urlparse(value)
    relative = PurePosixPath(parsed.path)
    if (
        parsed.scheme
        or parsed.netloc
        or parsed.query
        or parsed.fragment
        or relative.is_absolute()
        or not relative.parts
        or ".." in relative.parts
        or ":" in value
        or "\\" in value
    ):
        raise PackError(f"Pack Registry archive URL must be a safe relative path: {value}")
    return relative


def _safe_repository_path(value: str) -> str:
    normalized = value.strip().replace("\\", "/")
    path = PurePosixPath(normalized)
    if not normalized or path.is_absolute() or ".." in path.parts or ":" in normalized:
        raise PackError("GitHub Pages site path must be relative to the repository")
    return path.as_posix()


def _resolve_registry_file(root: Path, relative: PurePosixPath) -> Path:
    candidate = root.joinpath(*relative.parts)
    current = root
    for part in relative.parts:
        current = current / part
        if current.is_symlink():
            raise PackError(f"Pack Registry paths may not contain symbolic links: {relative}")
    resolved = candidate.resolve()
    if root != resolved and root not in resolved.parents:
        raise PackError(f"Pack Registry archive escapes its root: {relative}")
    return resolved


def _default_site_path(output_root: Path) -> str:
    if output_root.is_absolute():
        raise PackError("--site-path is required when --output-dir is absolute and a workflow is generated")
    return _safe_repository_path(output_root.as_posix())


def _validate_distinct_directories(source: Path, output: Path) -> None:
    if source == output or source in output.parents or output in source.parents:
        raise PackError("Registry source and Pages output directories must be separate and non-nested")


def _replace_managed_directory(temporary: Path, output: Path) -> None:
    if not output.exists():
        os.replace(temporary, output)
        return
    if not output.is_dir():
        raise PackError(f"GitHub Pages output is not a directory: {output}")
    if _same_tree(temporary, output):
        return
    entries = list(output.iterdir())
    if entries and not (output / _DEPLOYMENT_MARKER).is_file():
        raise PackError(f"Refusing to replace an unmanaged non-empty directory: {output}")
    backup = output.with_name(f".{output.name}.{uuid.uuid4().hex}.backup")
    os.replace(output, backup)
    try:
        os.replace(temporary, output)
    except Exception:
        os.replace(backup, output)
        raise
    finally:
        if backup.exists():
            shutil.rmtree(backup)


def _same_tree(left: Path, right: Path) -> bool:
    left_files = sorted(path.relative_to(left) for path in left.rglob("*") if path.is_file())
    right_files = sorted(path.relative_to(right) for path in right.rglob("*") if path.is_file())
    if left_files != right_files:
        return False
    return all(left.joinpath(path).read_bytes() == right.joinpath(path).read_bytes() for path in left_files)


def _github_pages_workflow(site_path: str) -> str:
    quoted_path = json.dumps(site_path, ensure_ascii=True)
    return f"""{_WORKFLOW_MARKER}
name: Deploy Pack Registry to GitHub Pages

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pack-registry-pages
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{{{ steps.deployment.outputs.page_url }}}}
    runs-on: ubuntu-latest
    steps:
      - name: Check out Registry
        uses: actions/checkout@v6
      - name: Configure Pages
        uses: actions/configure-pages@v5
      - name: Upload Registry artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: {quoted_path}
      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v4
"""
